// Code generated by mockery v2.53.5. DO NOT EDIT.

package interfaces

import (
	interfaces "github.com/hyperterse/hyperterse/core/domain/interfaces"
	hyperterse "github.com/hyperterse/hyperterse/core/proto/hyperterse"

	mock "github.com/stretchr/testify/mock"
)

// MockConnectorManager is an autogenerated mock type for the ConnectorManager type
type MockConnectorManager struct {
	mock.Mock
}

type MockConnectorManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectorManager) EXPECT() *MockConnectorManager_Expecter {
	return &MockConnectorManager_Expecter{mock: &_m.Mock}
}

// CloseAll provides a mock function with no fields
func (_m *MockConnectorManager) CloseAll() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnectorManager_CloseAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseAll'
type MockConnectorManager_CloseAll_Call struct {
	*mock.Call
}

// CloseAll is a helper method to define mock.On call
func (_e *MockConnectorManager_Expecter) CloseAll() *MockConnectorManager_CloseAll_Call {
	return &MockConnectorManager_CloseAll_Call{Call: _e.mock.On("CloseAll")}
}

func (_c *MockConnectorManager_CloseAll_Call) Run(run func()) *MockConnectorManager_CloseAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectorManager_CloseAll_Call) Return(_a0 error) *MockConnectorManager_CloseAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnectorManager_CloseAll_Call) RunAndReturn(run func() error) *MockConnectorManager_CloseAll_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function with no fields
func (_m *MockConnectorManager) Count() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockConnectorManager_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockConnectorManager_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
func (_e *MockConnectorManager_Expecter) Count() *MockConnectorManager_Count_Call {
	return &MockConnectorManager_Count_Call{Call: _e.mock.On("Count")}
}

func (_c *MockConnectorManager_Count_Call) Run(run func()) *MockConnectorManager_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectorManager_Count_Call) Return(_a0 int) *MockConnectorManager_Count_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnectorManager_Count_Call) RunAndReturn(run func() int) *MockConnectorManager_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: name
func (_m *MockConnectorManager) Get(name string) (interfaces.Connector, bool) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 interfaces.Connector
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (interfaces.Connector, bool)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) interfaces.Connector); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.Connector)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockConnectorManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockConnectorManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - name string
func (_e *MockConnectorManager_Expecter) Get(name interface{}) *MockConnectorManager_Get_Call {
	return &MockConnectorManager_Get_Call{Call: _e.mock.On("Get", name)}
}

func (_c *MockConnectorManager_Get_Call) Run(run func(name string)) *MockConnectorManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConnectorManager_Get_Call) Return(_a0 interfaces.Connector, _a1 bool) *MockConnectorManager_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectorManager_Get_Call) RunAndReturn(run func(string) (interfaces.Connector, bool)) *MockConnectorManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *MockConnectorManager) GetAll() map[string]interfaces.Connector {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]interfaces.Connector
	if rf, ok := ret.Get(0).(func() map[string]interfaces.Connector); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interfaces.Connector)
		}
	}

	return r0
}

// MockConnectorManager_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockConnectorManager_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockConnectorManager_Expecter) GetAll() *MockConnectorManager_GetAll_Call {
	return &MockConnectorManager_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockConnectorManager_GetAll_Call) Run(run func()) *MockConnectorManager_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectorManager_GetAll_Call) Return(_a0 map[string]interfaces.Connector) *MockConnectorManager_GetAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnectorManager_GetAll_Call) RunAndReturn(run func() map[string]interfaces.Connector) *MockConnectorManager_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeAll provides a mock function with given fields: adapters
func (_m *MockConnectorManager) InitializeAll(adapters []*hyperterse.Adapter) error {
	ret := _m.Called(adapters)

	if len(ret) == 0 {
		panic("no return value specified for InitializeAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*hyperterse.Adapter) error); ok {
		r0 = rf(adapters)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnectorManager_InitializeAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeAll'
type MockConnectorManager_InitializeAll_Call struct {
	*mock.Call
}

// InitializeAll is a helper method to define mock.On call
//   - adapters []*hyperterse.Adapter
func (_e *MockConnectorManager_Expecter) InitializeAll(adapters interface{}) *MockConnectorManager_InitializeAll_Call {
	return &MockConnectorManager_InitializeAll_Call{Call: _e.mock.On("InitializeAll", adapters)}
}

func (_c *MockConnectorManager_InitializeAll_Call) Run(run func(adapters []*hyperterse.Adapter)) *MockConnectorManager_InitializeAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*hyperterse.Adapter))
	})
	return _c
}

func (_c *MockConnectorManager_InitializeAll_Call) Return(_a0 error) *MockConnectorManager_InitializeAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnectorManager_InitializeAll_Call) RunAndReturn(run func([]*hyperterse.Adapter) error) *MockConnectorManager_InitializeAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnectorManager creates a new instance of MockConnectorManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectorManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectorManager {
	mock := &MockConnectorManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
