// Code generated by mockery v2.53.5. DO NOT EDIT.

package interfaces

import (
	context "context"

	hyperterse "github.com/hyperterse/hyperterse/core/proto/hyperterse"

	mock "github.com/stretchr/testify/mock"
)

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

type MockExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutor) EXPECT() *MockExecutor_Expecter {
	return &MockExecutor_Expecter{mock: &_m.Mock}
}

// ExecuteQuery provides a mock function with given fields: ctx, queryName, userInputs
func (_m *MockExecutor) ExecuteQuery(ctx context.Context, queryName string, userInputs map[string]interface{}) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, queryName, userInputs)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteQuery")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) ([]map[string]interface{}, error)); ok {
		return rf(ctx, queryName, userInputs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) []map[string]interface{}); ok {
		r0 = rf(ctx, queryName, userInputs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, queryName, userInputs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExecutor_ExecuteQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteQuery'
type MockExecutor_ExecuteQuery_Call struct {
	*mock.Call
}

// ExecuteQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - queryName string
//   - userInputs map[string]interface{}
func (_e *MockExecutor_Expecter) ExecuteQuery(ctx interface{}, queryName interface{}, userInputs interface{}) *MockExecutor_ExecuteQuery_Call {
	return &MockExecutor_ExecuteQuery_Call{Call: _e.mock.On("ExecuteQuery", ctx, queryName, userInputs)}
}

func (_c *MockExecutor_ExecuteQuery_Call) Run(run func(ctx context.Context, queryName string, userInputs map[string]interface{})) *MockExecutor_ExecuteQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockExecutor_ExecuteQuery_Call) Return(_a0 []map[string]interface{}, _a1 error) *MockExecutor_ExecuteQuery_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExecutor_ExecuteQuery_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) ([]map[string]interface{}, error)) *MockExecutor_ExecuteQuery_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllQueries provides a mock function with no fields
func (_m *MockExecutor) GetAllQueries() []*hyperterse.Query {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllQueries")
	}

	var r0 []*hyperterse.Query
	if rf, ok := ret.Get(0).(func() []*hyperterse.Query); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*hyperterse.Query)
		}
	}

	return r0
}

// MockExecutor_GetAllQueries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllQueries'
type MockExecutor_GetAllQueries_Call struct {
	*mock.Call
}

// GetAllQueries is a helper method to define mock.On call
func (_e *MockExecutor_Expecter) GetAllQueries() *MockExecutor_GetAllQueries_Call {
	return &MockExecutor_GetAllQueries_Call{Call: _e.mock.On("GetAllQueries")}
}

func (_c *MockExecutor_GetAllQueries_Call) Run(run func()) *MockExecutor_GetAllQueries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExecutor_GetAllQueries_Call) Return(_a0 []*hyperterse.Query) *MockExecutor_GetAllQueries_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutor_GetAllQueries_Call) RunAndReturn(run func() []*hyperterse.Query) *MockExecutor_GetAllQueries_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuery provides a mock function with given fields: queryName
func (_m *MockExecutor) GetQuery(queryName string) (*hyperterse.Query, error) {
	ret := _m.Called(queryName)

	if len(ret) == 0 {
		panic("no return value specified for GetQuery")
	}

	var r0 *hyperterse.Query
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*hyperterse.Query, error)); ok {
		return rf(queryName)
	}
	if rf, ok := ret.Get(0).(func(string) *hyperterse.Query); ok {
		r0 = rf(queryName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hyperterse.Query)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(queryName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExecutor_GetQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuery'
type MockExecutor_GetQuery_Call struct {
	*mock.Call
}

// GetQuery is a helper method to define mock.On call
//   - queryName string
func (_e *MockExecutor_Expecter) GetQuery(queryName interface{}) *MockExecutor_GetQuery_Call {
	return &MockExecutor_GetQuery_Call{Call: _e.mock.On("GetQuery", queryName)}
}

func (_c *MockExecutor_GetQuery_Call) Run(run func(queryName string)) *MockExecutor_GetQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockExecutor_GetQuery_Call) Return(_a0 *hyperterse.Query, _a1 error) *MockExecutor_GetQuery_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExecutor_GetQuery_Call) RunAndReturn(run func(string) (*hyperterse.Query, error)) *MockExecutor_GetQuery_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExecutor creates a new instance of MockExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutor {
	mock := &MockExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
