// Code generated by mockery v2.53.5. DO NOT EDIT.

package interfaces

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockConnector is an autogenerated mock type for the Connector type
type MockConnector struct {
	mock.Mock
}

type MockConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnector) EXPECT() *MockConnector_Expecter {
	return &MockConnector_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockConnector) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnector_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockConnector_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockConnector_Expecter) Close() *MockConnector_Close_Call {
	return &MockConnector_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockConnector_Close_Call) Run(run func()) *MockConnector_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnector_Close_Call) Return(_a0 error) *MockConnector_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnector_Close_Call) RunAndReturn(run func() error) *MockConnector_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields: ctx, statement, params
func (_m *MockConnector) Execute(ctx context.Context, statement string, params map[string]interface{}) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, statement, params)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) ([]map[string]interface{}, error)); ok {
		return rf(ctx, statement, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) []map[string]interface{}); ok {
		r0 = rf(ctx, statement, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, statement, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnector_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockConnector_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - statement string
//   - params map[string]interface{}
func (_e *MockConnector_Expecter) Execute(ctx interface{}, statement interface{}, params interface{}) *MockConnector_Execute_Call {
	return &MockConnector_Execute_Call{Call: _e.mock.On("Execute", ctx, statement, params)}
}

func (_c *MockConnector_Execute_Call) Run(run func(ctx context.Context, statement string, params map[string]interface{})) *MockConnector_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockConnector_Execute_Call) Return(_a0 []map[string]interface{}, _a1 error) *MockConnector_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnector_Execute_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) ([]map[string]interface{}, error)) *MockConnector_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnector creates a new instance of MockConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnector {
	mock := &MockConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
