// Code generated by mockery v2.53.5. DO NOT EDIT.

package interfaces

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	runtime "github.com/hyperterse/hyperterse/core/proto/runtime"
)

// MockMCPService is an autogenerated mock type for the MCPService type
type MockMCPService struct {
	mock.Mock
}

type MockMCPService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMCPService) EXPECT() *MockMCPService_Expecter {
	return &MockMCPService_Expecter{mock: &_m.Mock}
}

// CallTool provides a mock function with given fields: ctx, req
func (_m *MockMCPService) CallTool(ctx context.Context, req *runtime.CallToolRequest) (*runtime.CallToolResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CallTool")
	}

	var r0 *runtime.CallToolResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *runtime.CallToolRequest) (*runtime.CallToolResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *runtime.CallToolRequest) *runtime.CallToolResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*runtime.CallToolResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *runtime.CallToolRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMCPService_CallTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallTool'
type MockMCPService_CallTool_Call struct {
	*mock.Call
}

// CallTool is a helper method to define mock.On call
//   - ctx context.Context
//   - req *runtime.CallToolRequest
func (_e *MockMCPService_Expecter) CallTool(ctx interface{}, req interface{}) *MockMCPService_CallTool_Call {
	return &MockMCPService_CallTool_Call{Call: _e.mock.On("CallTool", ctx, req)}
}

func (_c *MockMCPService_CallTool_Call) Run(run func(ctx context.Context, req *runtime.CallToolRequest)) *MockMCPService_CallTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*runtime.CallToolRequest))
	})
	return _c
}

func (_c *MockMCPService_CallTool_Call) Return(_a0 *runtime.CallToolResponse, _a1 error) *MockMCPService_CallTool_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMCPService_CallTool_Call) RunAndReturn(run func(context.Context, *runtime.CallToolRequest) (*runtime.CallToolResponse, error)) *MockMCPService_CallTool_Call {
	_c.Call.Return(run)
	return _c
}

// ListTools provides a mock function with given fields: ctx, req
func (_m *MockMCPService) ListTools(ctx context.Context, req *runtime.ListToolsRequest) (*runtime.ListToolsResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListTools")
	}

	var r0 *runtime.ListToolsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *runtime.ListToolsRequest) (*runtime.ListToolsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *runtime.ListToolsRequest) *runtime.ListToolsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*runtime.ListToolsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *runtime.ListToolsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMCPService_ListTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTools'
type MockMCPService_ListTools_Call struct {
	*mock.Call
}

// ListTools is a helper method to define mock.On call
//   - ctx context.Context
//   - req *runtime.ListToolsRequest
func (_e *MockMCPService_Expecter) ListTools(ctx interface{}, req interface{}) *MockMCPService_ListTools_Call {
	return &MockMCPService_ListTools_Call{Call: _e.mock.On("ListTools", ctx, req)}
}

func (_c *MockMCPService_ListTools_Call) Run(run func(ctx context.Context, req *runtime.ListToolsRequest)) *MockMCPService_ListTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*runtime.ListToolsRequest))
	})
	return _c
}

func (_c *MockMCPService_ListTools_Call) Return(_a0 *runtime.ListToolsResponse, _a1 error) *MockMCPService_ListTools_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMCPService_ListTools_Call) RunAndReturn(run func(context.Context, *runtime.ListToolsRequest) (*runtime.ListToolsResponse, error)) *MockMCPService_ListTools_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMCPService creates a new instance of MockMCPService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMCPService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMCPService {
	mock := &MockMCPService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
