// Code generated by mockery v2.53.5. DO NOT EDIT.

package interfaces

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	runtime "github.com/hyperterse/hyperterse/core/proto/runtime"
)

// MockQueryService is an autogenerated mock type for the QueryService type
type MockQueryService struct {
	mock.Mock
}

type MockQueryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryService) EXPECT() *MockQueryService_Expecter {
	return &MockQueryService_Expecter{mock: &_m.Mock}
}

// ExecuteQuery provides a mock function with given fields: ctx, req
func (_m *MockQueryService) ExecuteQuery(ctx context.Context, req *runtime.ExecuteQueryRequest) (*runtime.ExecuteQueryResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteQuery")
	}

	var r0 *runtime.ExecuteQueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *runtime.ExecuteQueryRequest) (*runtime.ExecuteQueryResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *runtime.ExecuteQueryRequest) *runtime.ExecuteQueryResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*runtime.ExecuteQueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *runtime.ExecuteQueryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueryService_ExecuteQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteQuery'
type MockQueryService_ExecuteQuery_Call struct {
	*mock.Call
}

// ExecuteQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - req *runtime.ExecuteQueryRequest
func (_e *MockQueryService_Expecter) ExecuteQuery(ctx interface{}, req interface{}) *MockQueryService_ExecuteQuery_Call {
	return &MockQueryService_ExecuteQuery_Call{Call: _e.mock.On("ExecuteQuery", ctx, req)}
}

func (_c *MockQueryService_ExecuteQuery_Call) Run(run func(ctx context.Context, req *runtime.ExecuteQueryRequest)) *MockQueryService_ExecuteQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*runtime.ExecuteQueryRequest))
	})
	return _c
}

func (_c *MockQueryService_ExecuteQuery_Call) Return(_a0 *runtime.ExecuteQueryResponse, _a1 error) *MockQueryService_ExecuteQuery_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueryService_ExecuteQuery_Call) RunAndReturn(run func(context.Context, *runtime.ExecuteQueryRequest) (*runtime.ExecuteQueryResponse, error)) *MockQueryService_ExecuteQuery_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueryService creates a new instance of MockQueryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryService {
	mock := &MockQueryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
