// Code generated by mockery v2.53.5. DO NOT EDIT.

package interfaces

import mock "github.com/stretchr/testify/mock"

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function with given fields: message
func (_m *MockLogger) Debug(message string) {
	_m.Called(message)
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - message string
func (_e *MockLogger_Expecter) Debug(message interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug", message)}
}

func (_c *MockLogger_Debug_Call) Run(run func(message string)) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(string)) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Debugf provides a mock function with given fields: format, args
func (_m *MockLogger) Debugf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Debugf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugf'
type MockLogger_Debugf_Call struct {
	*mock.Call
}

// Debugf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Debugf(format interface{}, args ...interface{}) *MockLogger_Debugf_Call {
	return &MockLogger_Debugf_Call{Call: _e.mock.On("Debugf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Debugf_Call) Run(run func(format string, args ...interface{})) *MockLogger_Debugf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Debugf_Call) Return() *MockLogger_Debugf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debugf_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Debugf_Call {
	_c.Run(run)
	return _c
}

// Debugln provides a mock function with given fields: args
func (_m *MockLogger) Debugln(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Debugln_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugln'
type MockLogger_Debugln_Call struct {
	*mock.Call
}

// Debugln is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLogger_Expecter) Debugln(args ...interface{}) *MockLogger_Debugln_Call {
	return &MockLogger_Debugln_Call{Call: _e.mock.On("Debugln",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Debugln_Call) Run(run func(args ...interface{})) *MockLogger_Debugln_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Debugln_Call) Return() *MockLogger_Debugln_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debugln_Call) RunAndReturn(run func(...interface{})) *MockLogger_Debugln_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function with given fields: message
func (_m *MockLogger) Error(message string) {
	_m.Called(message)
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - message string
func (_e *MockLogger_Expecter) Error(message interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error", message)}
}

func (_c *MockLogger_Error_Call) Run(run func(message string)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(string)) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Errorf provides a mock function with given fields: format, args
func (_m *MockLogger) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Errorf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorf'
type MockLogger_Errorf_Call struct {
	*mock.Call
}

// Errorf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Errorf(format interface{}, args ...interface{}) *MockLogger_Errorf_Call {
	return &MockLogger_Errorf_Call{Call: _e.mock.On("Errorf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Errorf_Call) Run(run func(format string, args ...interface{})) *MockLogger_Errorf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Errorf_Call) Return() *MockLogger_Errorf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Errorf_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Errorf_Call {
	_c.Run(run)
	return _c
}

// Errorln provides a mock function with given fields: args
func (_m *MockLogger) Errorln(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Errorln_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorln'
type MockLogger_Errorln_Call struct {
	*mock.Call
}

// Errorln is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLogger_Expecter) Errorln(args ...interface{}) *MockLogger_Errorln_Call {
	return &MockLogger_Errorln_Call{Call: _e.mock.On("Errorln",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Errorln_Call) Run(run func(args ...interface{})) *MockLogger_Errorln_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Errorln_Call) Return() *MockLogger_Errorln_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Errorln_Call) RunAndReturn(run func(...interface{})) *MockLogger_Errorln_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function with given fields: message
func (_m *MockLogger) Info(message string) {
	_m.Called(message)
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - message string
func (_e *MockLogger_Expecter) Info(message interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info", message)}
}

func (_c *MockLogger_Info_Call) Run(run func(message string)) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(string)) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// Infof provides a mock function with given fields: format, args
func (_m *MockLogger) Infof(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Infof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infof'
type MockLogger_Infof_Call struct {
	*mock.Call
}

// Infof is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Infof(format interface{}, args ...interface{}) *MockLogger_Infof_Call {
	return &MockLogger_Infof_Call{Call: _e.mock.On("Infof",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Infof_Call) Run(run func(format string, args ...interface{})) *MockLogger_Infof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Infof_Call) Return() *MockLogger_Infof_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Infof_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Infof_Call {
	_c.Run(run)
	return _c
}

// Infoln provides a mock function with given fields: args
func (_m *MockLogger) Infoln(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Infoln_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infoln'
type MockLogger_Infoln_Call struct {
	*mock.Call
}

// Infoln is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLogger_Expecter) Infoln(args ...interface{}) *MockLogger_Infoln_Call {
	return &MockLogger_Infoln_Call{Call: _e.mock.On("Infoln",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Infoln_Call) Run(run func(args ...interface{})) *MockLogger_Infoln_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Infoln_Call) Return() *MockLogger_Infoln_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Infoln_Call) RunAndReturn(run func(...interface{})) *MockLogger_Infoln_Call {
	_c.Run(run)
	return _c
}

// Multiline provides a mock function with given fields: lines
func (_m *MockLogger) Multiline(lines []interface{}) {
	_m.Called(lines)
}

// MockLogger_Multiline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Multiline'
type MockLogger_Multiline_Call struct {
	*mock.Call
}

// Multiline is a helper method to define mock.On call
//   - lines []interface{}
func (_e *MockLogger_Expecter) Multiline(lines interface{}) *MockLogger_Multiline_Call {
	return &MockLogger_Multiline_Call{Call: _e.mock.On("Multiline", lines)}
}

func (_c *MockLogger_Multiline_Call) Run(run func(lines []interface{})) *MockLogger_Multiline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]interface{}))
	})
	return _c
}

func (_c *MockLogger_Multiline_Call) Return() *MockLogger_Multiline_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Multiline_Call) RunAndReturn(run func([]interface{})) *MockLogger_Multiline_Call {
	_c.Run(run)
	return _c
}

// PrintError provides a mock function with given fields: title, err
func (_m *MockLogger) PrintError(title string, err error) {
	_m.Called(title, err)
}

// MockLogger_PrintError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrintError'
type MockLogger_PrintError_Call struct {
	*mock.Call
}

// PrintError is a helper method to define mock.On call
//   - title string
//   - err error
func (_e *MockLogger_Expecter) PrintError(title interface{}, err interface{}) *MockLogger_PrintError_Call {
	return &MockLogger_PrintError_Call{Call: _e.mock.On("PrintError", title, err)}
}

func (_c *MockLogger_PrintError_Call) Run(run func(title string, err error)) *MockLogger_PrintError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(error))
	})
	return _c
}

func (_c *MockLogger_PrintError_Call) Return() *MockLogger_PrintError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_PrintError_Call) RunAndReturn(run func(string, error)) *MockLogger_PrintError_Call {
	_c.Run(run)
	return _c
}

// PrintSuccess provides a mock function with given fields: message
func (_m *MockLogger) PrintSuccess(message string) {
	_m.Called(message)
}

// MockLogger_PrintSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrintSuccess'
type MockLogger_PrintSuccess_Call struct {
	*mock.Call
}

// PrintSuccess is a helper method to define mock.On call
//   - message string
func (_e *MockLogger_Expecter) PrintSuccess(message interface{}) *MockLogger_PrintSuccess_Call {
	return &MockLogger_PrintSuccess_Call{Call: _e.mock.On("PrintSuccess", message)}
}

func (_c *MockLogger_PrintSuccess_Call) Run(run func(message string)) *MockLogger_PrintSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLogger_PrintSuccess_Call) Return() *MockLogger_PrintSuccess_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_PrintSuccess_Call) RunAndReturn(run func(string)) *MockLogger_PrintSuccess_Call {
	_c.Run(run)
	return _c
}

// PrintValidationErrors provides a mock function with given fields: errors
func (_m *MockLogger) PrintValidationErrors(errors []string) {
	_m.Called(errors)
}

// MockLogger_PrintValidationErrors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrintValidationErrors'
type MockLogger_PrintValidationErrors_Call struct {
	*mock.Call
}

// PrintValidationErrors is a helper method to define mock.On call
//   - errors []string
func (_e *MockLogger_Expecter) PrintValidationErrors(errors interface{}) *MockLogger_PrintValidationErrors_Call {
	return &MockLogger_PrintValidationErrors_Call{Call: _e.mock.On("PrintValidationErrors", errors)}
}

func (_c *MockLogger_PrintValidationErrors_Call) Run(run func(errors []string)) *MockLogger_PrintValidationErrors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockLogger_PrintValidationErrors_Call) Return() *MockLogger_PrintValidationErrors_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_PrintValidationErrors_Call) RunAndReturn(run func([]string)) *MockLogger_PrintValidationErrors_Call {
	_c.Run(run)
	return _c
}

// Printf provides a mock function with given fields: format, args
func (_m *MockLogger) Printf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Printf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Printf'
type MockLogger_Printf_Call struct {
	*mock.Call
}

// Printf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Printf(format interface{}, args ...interface{}) *MockLogger_Printf_Call {
	return &MockLogger_Printf_Call{Call: _e.mock.On("Printf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Printf_Call) Run(run func(format string, args ...interface{})) *MockLogger_Printf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Printf_Call) Return() *MockLogger_Printf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Printf_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Printf_Call {
	_c.Run(run)
	return _c
}

// Println provides a mock function with given fields: args
func (_m *MockLogger) Println(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Println_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Println'
type MockLogger_Println_Call struct {
	*mock.Call
}

// Println is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLogger_Expecter) Println(args ...interface{}) *MockLogger_Println_Call {
	return &MockLogger_Println_Call{Call: _e.mock.On("Println",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Println_Call) Run(run func(args ...interface{})) *MockLogger_Println_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Println_Call) Return() *MockLogger_Println_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Println_Call) RunAndReturn(run func(...interface{})) *MockLogger_Println_Call {
	_c.Run(run)
	return _c
}

// Success provides a mock function with given fields: message
func (_m *MockLogger) Success(message string) {
	_m.Called(message)
}

// MockLogger_Success_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Success'
type MockLogger_Success_Call struct {
	*mock.Call
}

// Success is a helper method to define mock.On call
//   - message string
func (_e *MockLogger_Expecter) Success(message interface{}) *MockLogger_Success_Call {
	return &MockLogger_Success_Call{Call: _e.mock.On("Success", message)}
}

func (_c *MockLogger_Success_Call) Run(run func(message string)) *MockLogger_Success_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLogger_Success_Call) Return() *MockLogger_Success_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Success_Call) RunAndReturn(run func(string)) *MockLogger_Success_Call {
	_c.Run(run)
	return _c
}

// Successf provides a mock function with given fields: format, args
func (_m *MockLogger) Successf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Successf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Successf'
type MockLogger_Successf_Call struct {
	*mock.Call
}

// Successf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Successf(format interface{}, args ...interface{}) *MockLogger_Successf_Call {
	return &MockLogger_Successf_Call{Call: _e.mock.On("Successf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Successf_Call) Run(run func(format string, args ...interface{})) *MockLogger_Successf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Successf_Call) Return() *MockLogger_Successf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Successf_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Successf_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function with given fields: message
func (_m *MockLogger) Warn(message string) {
	_m.Called(message)
}

// MockLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - message string
func (_e *MockLogger_Expecter) Warn(message interface{}) *MockLogger_Warn_Call {
	return &MockLogger_Warn_Call{Call: _e.mock.On("Warn", message)}
}

func (_c *MockLogger_Warn_Call) Run(run func(message string)) *MockLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLogger_Warn_Call) Return() *MockLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warn_Call) RunAndReturn(run func(string)) *MockLogger_Warn_Call {
	_c.Run(run)
	return _c
}

// Warnf provides a mock function with given fields: format, args
func (_m *MockLogger) Warnf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Warnf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warnf'
type MockLogger_Warnf_Call struct {
	*mock.Call
}

// Warnf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Warnf(format interface{}, args ...interface{}) *MockLogger_Warnf_Call {
	return &MockLogger_Warnf_Call{Call: _e.mock.On("Warnf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Warnf_Call) Run(run func(format string, args ...interface{})) *MockLogger_Warnf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Warnf_Call) Return() *MockLogger_Warnf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warnf_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Warnf_Call {
	_c.Run(run)
	return _c
}

// Warnln provides a mock function with given fields: args
func (_m *MockLogger) Warnln(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Warnln_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warnln'
type MockLogger_Warnln_Call struct {
	*mock.Call
}

// Warnln is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLogger_Expecter) Warnln(args ...interface{}) *MockLogger_Warnln_Call {
	return &MockLogger_Warnln_Call{Call: _e.mock.On("Warnln",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Warnln_Call) Run(run func(args ...interface{})) *MockLogger_Warnln_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Warnln_Call) Return() *MockLogger_Warnln_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warnln_Call) RunAndReturn(run func(...interface{})) *MockLogger_Warnln_Call {
	_c.Run(run)
	return _c
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
