version: '2'

run:
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - unconvert
    - prealloc
    - exportloopref
    - gocritic
    - gocyclo
    - dupl
    - goerr113
    - nolintlint
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - varnamelen
    - whitespace
  settings:
    revive:
      rules:
        - name: exported
          severity: warning
        - name: var-naming
          severity: warning
        - name: package-comments
          severity: warning
        - name: error-return
          severity: warning
        - name: receiver-naming
          severity: warning
        - name: if-return
          severity: warning
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    misspell:
      locale: US
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gocyclo
          - dupl
      - path: (^|/)mocks/
        linters:
          - all

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
