name: Feature Request
description: Suggest a new feature or enhancement for Hyperterse
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What use case does it address?
      placeholder: Describe the problem or use case that this feature would address...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution or feature implementation...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions or features you've considered...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or screenshots about the feature request here.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have checked the documentation to see if this feature is already documented
          required: false
        - label: I'm willing to help implement this feature if needed
          required: false
