# typed: false
# frozen_string_literal: true

# This file was generated by Hyperterse. It is a bare minimum Homebrew formula.
# Documentation: https://docs.brew.sh/Formula-Cookbook
# This file is automatically updated by scripts/version.sh

class Hyperterse < Formula
  desc "A declarative interface to connect your database to your AI agents"
  homepage "https://hyperterse.com"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hyperterse/hyperterse/releases/download/v#{version}/hyperterse-darwin-amd64"
      sha256 ""
    elsif Hardware::CPU.arm?
      url "https://github.com/hyperterse/hyperterse/releases/download/v#{version}/hyperterse-darwin-arm64"
      sha256 ""
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hyperterse/hyperterse/releases/download/v#{version}/hyperterse-linux-amd64"
      sha256 ""
    elsif Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hyperterse/hyperterse/releases/download/v#{version}/hyperterse-linux-arm64"
        sha256 ""
      else
        url "https://github.com/hyperterse/hyperterse/releases/download/v#{version}/hyperterse-linux-arm"
        sha256 ""
      end
    end
  end

  def install
    # Homebrew downloads the binary file, rename it to 'hyperterse'
    binary = Dir["hyperterse-*"].first
    bin.install binary => "hyperterse"
  end

  test do
    system "#{bin}/hyperterse", "--version"
  end
end
