name: 'Publish to Homebrew'
description: 'Publish formula to Homebrew tap repository'
inputs:
  version:
    description: 'Version to publish'
    required: true
  token:
    description: 'GitHub token for accessing tap repository'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download checksums.txt from release
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        mkdir -p dist

        # Download checksums.txt from GitHub release
        echo "Downloading checksums.txt from release v${VERSION}..."
        curl -L -f -o dist/checksums.txt \
          "https://github.com/${{ github.repository }}/releases/download/v${VERSION}/checksums.txt"
        echo "✓ Downloaded checksums.txt"

    - name: Parse checksums from checksums.txt
      id: sha256
      shell: bash
      run: |
        cd dist
        # Parse checksums for binaries (not tar.gz files)
        # Match exact binary names to avoid matching arm64 when looking for arm
        SHA256_DARWIN_AMD64=$(grep -E "hyperterse-darwin-amd64$" checksums.txt | awk '{print $1}' || echo "")
        SHA256_DARWIN_ARM64=$(grep -E "hyperterse-darwin-arm64$" checksums.txt | awk '{print $1}' || echo "")
        SHA256_LINUX_AMD64=$(grep -E "hyperterse-linux-amd64$" checksums.txt | awk '{print $1}' || echo "")
        SHA256_LINUX_ARM64=$(grep -E "hyperterse-linux-arm64$" checksums.txt | awk '{print $1}' || echo "")
        # For linux-arm, match exactly "hyperterse-linux-arm" (not arm64)
        SHA256_LINUX_ARM=$(grep "hyperterse-linux-arm$" checksums.txt | grep -v "arm64" | awk '{print $1}' || echo "")

        echo "darwin_amd64=${SHA256_DARWIN_AMD64}" >> $GITHUB_OUTPUT
        echo "darwin_arm64=${SHA256_DARWIN_ARM64}" >> $GITHUB_OUTPUT
        echo "linux_amd64=${SHA256_LINUX_AMD64}" >> $GITHUB_OUTPUT
        echo "linux_arm64=${SHA256_LINUX_ARM64}" >> $GITHUB_OUTPUT
        echo "linux_arm=${SHA256_LINUX_ARM}" >> $GITHUB_OUTPUT

        # Verify we got all checksums
        if [ -z "${SHA256_DARWIN_AMD64}" ] || [ -z "${SHA256_DARWIN_ARM64}" ] || [ -z "${SHA256_LINUX_AMD64}" ] || [ -z "${SHA256_LINUX_ARM64}" ] || [ -z "${SHA256_LINUX_ARM}" ]; then
          echo "❌ Failed to extract all checksums from checksums.txt"
          exit 1
        fi
        echo "✓ Extracted all checksums from checksums.txt"

    - name: Verify version in formula
      shell: bash
      run: |
        FORMULA_VERSION=$(grep -E '^\s+version\s+"[^"]+"' distributions/homebrew/hyperterse.rb | sed -E 's/.*version\s+"([^"]+)".*/\1/')
        EXPECTED_VERSION="${{ inputs.version }}"
        if [ "$FORMULA_VERSION" != "$EXPECTED_VERSION" ]; then
          echo "❌ Version mismatch: formula has $FORMULA_VERSION but expected $EXPECTED_VERSION"
          exit 1
        fi
        echo "✓ Version matches: $FORMULA_VERSION"

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2

    - name: Update Homebrew formula with SHA256
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        FORMULA_FILE="distributions/homebrew/hyperterse.rb"

        # Update version (if not already correct)
        sed -i "s/^  version \".*\"/  version \"${VERSION}\"/" "$FORMULA_FILE"

        # Update SHA256 checksums using helper script
        bun run scripts/update-homebrew-sha256.ts \
          "$FORMULA_FILE" \
          "${{ steps.sha256.outputs.darwin_amd64 }}" \
          "${{ steps.sha256.outputs.darwin_arm64 }}" \
          "${{ steps.sha256.outputs.linux_amd64 }}" \
          "${{ steps.sha256.outputs.linux_arm64 }}" \
          "${{ steps.sha256.outputs.linux_arm }}"

    - name: Checkout homebrew-tap
      uses: actions/checkout@v4
      with:
        repository: 'hyperterse/homebrew-tap'
        token: ${{ inputs.token }}
        path: homebrew-tap

    - name: Copy formula to tap
      shell: bash
      run: |
        mkdir -p homebrew-tap
        cp distributions/homebrew/hyperterse.rb homebrew-tap/hyperterse.rb

    - name: Commit and push to tap
      shell: bash
      run: |
        cd homebrew-tap
        git config user.name "hyperterse"
        git config user.email "bot@hyperterse.com"
        git add hyperterse.rb
        if ! git diff --staged --quiet; then
          git commit -m "Update hyperterse to v${{ inputs.version }}"
          git push
        else
          echo "No changes to commit"
        fi
